const API_BASE_URL = 'http://172.20.10.5:3000';                           ////////here////////
export const API_BASE_URL_HTML = 'http://172.20.10.5:3001';
// const API_BASE_URL = 'http://172.20.10.5:3000'; 
const API_ENDPOINTS = {
  write_comment: `${API_BASE_URL}/write_comment`,
  user_plays: (userId) => `${API_BASE_URL}/user/plays/${userId}`,
  a_profile: (userId) => `${API_BASE_URL}/a_user_data/${userId}`,  
  login: `${API_BASE_URL}/login`,
  adminSearch: `${API_BASE_URL}/admin-search`,
  adminSuspend: `${API_BASE_URL}/admin-suspend`,
  signup: `${API_BASE_URL}/signup`,
  edit_user_profile: `${API_BASE_URL}/edit_user_profile`,
  all_profile: `${API_BASE_URL}/all_user_data`,
  edit_email: `${API_BASE_URL}/edit-email`,
  edit_game: `${API_BASE_URL}/edit_game`,
  edit_password: `${API_BASE_URL}/edit-password`,
  all_profiles: `${API_BASE_URL}/all_users_data`,
  profile: `${API_BASE_URL}/profile`,
  top_player: `${API_BASE_URL}/top-player`,
  profile_all: `${API_BASE_URL}/profile_all`,
  get_notifications: `${API_BASE_URL}/get_notifications`,
  create_notification: `${API_BASE_URL}/create_notification`,
  session_user_made_games: `${API_BASE_URL}/session_user_made_games`,
  get_games_by_session: `${API_BASE_URL}/get_games_by_session`,
  game_create: `${API_BASE_URL}/game/new`, 
  png_create: `${API_BASE_URL}/game/convert-svg-to-png`,
  add_asset: `${API_BASE_URL}/user/add_asset`, 
  check_user_collected_asset: `${API_BASE_URL}/user/check_user_collected_asset`,
  send_report: `${API_BASE_URL}/user/send_report`,
  user_games: (userId) => `${API_BASE_URL}/user/games/${userId}`, 
  get_comments_for_game: (gameId) => `${API_BASE_URL}/get_comments_for_game/${gameId}`, 
  get_draws: (userId) => `${API_BASE_URL}/user/get_draws/${userId}`,
  get_last_10_assets_for_user: (user_id) => `${API_BASE_URL}/user/get_last_10_assets_for_user/${user_id}`,
  delete_asset: (id) => `${API_BASE_URL}/game/delete_asset/${id}`,
  game_details: (gameId) => `${API_BASE_URL}/game/game_details/${gameId}`,
  get_assets_for_game: (game_id) => `${API_BASE_URL}/game/get_assets_for_game/${game_id}`,
  join_game: (gameId) => `${API_BASE_URL}/join_game/${gameId}`, 
  top_10_most_liked_games: `${API_BASE_URL}/top_10_most_liked_games`,
};

export default API_ENDPOINTS;
